name: Rocket League Fan Rewards

on:
  push:
    branches: [gh-pages]
  schedule:
  - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install Jinja2 twitchAPI
    - name: Execute
      run: |
        python RocketLeagueFanRewards.py --appid ${{ secrets.APP_ID }} --appsecret ${{ secrets.APP_SECRET }}
    - name: Commit changes
      run: |
        git config --global user.name 'haltepunkt'
        git config --global user.email '33886909+haltepunkt@users.noreply.github.com'
        git add 'index.html'
        git commit -m "`date +'%Y-%m-%d %H:%M:%S'`"
        git push
